return {
	mod_description = {
		en = "Adds visual representation of current aiming direction of the player.",
		fr = "Ajoute une représentation visuelle de la direction de visée actuelle du joueur.",
		de = "Fügt eine visuelle Darstellung der aktuellen Zielrichtung des Spielers hinzu.",
		es = "Agrega una representación visual de la dirección de orientación actual del jugador.",
		ru = "Добавляет визуальное представление текущего направленного направления игрока.",
		it = "Aggiunge la rappresentazione visiva dell'attuale direzione di puntamento del giocatore.",
		pl = "Dodaje wizualną reprezentację kierunku, w którym celuje gracz.",
		["br-pt"] = "Adiciona uma representação visual da direção de mira atual do jogador.",
	},
	distance_option_name = {
		en = "Line length",
		fr = "Longueur de la ligne",
		de = "Linienlänge",
		es = "Longitud de la línea",
		ru = "Длина линии",
		it = "Lunghezza della linea",
		pl = "Długość linii",
		["br-pt"] = "Comprimento da linha",		
	},
	distance_option_tooltip = {
		en = "Determines length of the line drawn from player's view point.",
		fr = "Détermine la longueur de la ligne tirée du point de vue des joueurs.",
		de = "Bestimmt die Länge der Linie, die vom Standpunkt des Spielers aus gezeichnet wird.",
		es = "Determina la longitud de la línea dibujada desde el punto de vista de los jugadores.",
		ru = "Определяет длину линии, взятой из точки просмотра игроков.",
		it = "Determina la lunghezza della linea tracciata dal punto di vista dei giocatori.",
		pl = "Określa długość linii prowadzonej z punktu widzenia gracza.",
		["br-pt"] = "Determina o comprimento da linha desenhada a partir do ponto de vista do jogador.",			
	},
	opacity_option_name = {
		en = "Opacity",
		fr = "Opacité",
		de = "Opazität",
		es = "Opacidad",
		ru = "помутнение",
		it = "Opacità",
		pl = "Przezroczystość",
		["br-pt"] = "Opacidade",		
	},
	opacity_option_tooltip = {
		en = "Determines opacity of drawn lines.",
		fr = "Détermine l'opacité des lignes tracées.",
		de = "Bestimmt die Deckkraft von gezeichneten Linien.",
		es = "Determina la opacidad de las líneas dibujadas.",
		ru = "Определяет непрозрачность рисованных линий.",
		it = "Determina l'opacità delle linee disegnate.",
		pl = "Określa przezroczystość rysowanych linii.",
		["br-pt"] = "Determina a opacidade das linhas desenhadas.",			
	},	
	rangedonly_option_name = {
		en = "Only show for ranged weapons",
		fr = "Afficher uniquement pour les armes à distance",
		de = "Zeige nur für Fernwaffen",
		es = "Mostrar solo para armas a distancia",
		ru = "Показывать только оружие дальнего боя",
		it = "Mostra solo per armi a distanza",
		pl = "Tylko pokazuj dla broni dystansowych",
		["br-pt"] = "Mostrar apenas para armas de longo alcance",		
	},
	rangedonly_option_tooltip = {
		en = "Lines will only be drawn for players which are currently using ranged weapons.",
		fr = "Les lignes ne seront dessinées que pour les joueurs qui utilisent actuellement des armes à distance.",
		de = "Linien werden nur für Spieler gezogen, die derzeit Fernkampfwaffen benutzen.",
		es = "Las líneas solo se dibujarán para los jugadores que actualmente usan armas a distancia.",
		ru = "Линии будут отображаться только для игроков, которые в настоящее время используют оружие дальнего боя.",
		it = "Le linee verranno sorteggiate solo per i giocatori che stanno attualmente utilizzando armi a distanza.",
		pl = "Linie będą rysowane tylko dla graczy gdy korzystają z broni dystansowych.",
		["br-pt"] = "As linhas só serão sorteadas para jogadores que estejam usando armas de longo alcance.",			
	},		
}